// Top-bar modules and each module's sidebar. Feature labels are the existing step names in each page.
export const MODULES = [
  {
    id: 'design',
    tab: 'DESIGN',
    title: 'Design',
    subtitle: 'Protocol & Study Design',
    features: [
      { id: 'extract', label: 'Step 1: Protocol Review' },
      { id: 'summary', label: 'Step 2: Protocol Synopsis' },
      { id: 'eligibility', label: 'Step 3: Eligibility Criteria Review' },
      { id: 'gaps', label: 'Step 4: Protocol Gap Assessment' },
      { id: 'feasibility', label: 'Step 5: Study Feasibility Review' },
      { id: 'recommendations', label: 'Step 6: Study Design Optimization' },
      { id: 'chat', label: 'Ask AI' },
    ],
  },
  {
    id: 'find',
    tab: 'FIND',
    title: 'Find',
    subtitle: 'Trial Search',
    features: [
      { id: 'results', label: 'Step 1: Search Results' },
      { id: 'metadata', label: 'Step 2: Metadata' },
      { id: 'summary', label: 'Step 3: Summary' },
      { id: 'similar', label: 'Step 4: Similar Trials' },
      { id: 'comparison', label: 'Step 5: Comparison' },
      { id: 'recruiting', label: 'Step 6: Recruiting' },
      { id: 'gaps', label: 'Step 7: Gaps' },
      { id: 'topics', label: 'Step 8: Topics' },
      { id: 'dissertation', label: 'Step 9: Dissertation' },
      { id: 'chat', label: 'Ask AI' },
    ],
  },
  {
    id: 'manage',
    tab: 'MANAGE',
    title: 'Manage',
    subtitle: 'Data Management',
    features: [
      { id: 'crf_review', label: 'Step 1: CRF Review' },
      { id: 'edit_checks', label: 'Step 2: Edit Checks' },
      { id: 'query_wording', label: 'Step 3: Query Wording' },
      { id: 'cleaning_checklist', label: 'Step 4: Cleaning Checklist' },
      { id: 'medical_coding', label: 'Step 5: Coding Review' },
      { id: 'dataset_review', label: 'Step 6: Dataset Review' },
      { id: 'review_summary', label: 'Step 7: Review Summary' },
    ],
  },
  {
    id: 'analyze',
    tab: 'ANALYSE',
    title: 'Analyse',
    subtitle: 'Biostatistics',
    features: [
      { id: 'study_review', label: '1. Study Analysis Review' },
      { id: 'endpoint_summary', label: '2. Endpoint Summary' },
      { id: 'sap_outline', label: '3. SAP Outline Structure' },
      { id: 'tlf_shells', label: '4. TLF Shell Draft Package' },
      { id: 'dataset_checklist', label: '5. Dataset Review Checklist' },
      { id: 'descriptive_stats', label: '6. Descriptive Statistics' },
      { id: 'clinical_interpretation', label: '7. Clinical Interpretation' },
      { id: 'csr_results', label: '8. CSR Results Draft' },
      { id: 'chat', label: 'Biostatistician Chat' },
    ],
  },
  {
    id: 'safety',
    tab: 'SAFETY',
    title: 'Safety',
    subtitle: 'Pharmacovigilance',
    features: [
      { id: '1', label: '1. Safety Case Review' },
      { id: '2', label: '2. SAE Narrative Draft' },
      { id: '3', label: '3. Safety Case Summary' },
      { id: '4', label: '4. Seriousness & Causality' },
      { id: '5', label: '5. MedDRA Coding Support' },
      { id: '6', label: '6. Aggregate Safety Summary' },
      { id: '7', label: '7. Safety Trend Analysis' },
      { id: '8', label: '8. Medical Review Note' },
      { id: '9', label: '9. Signal Detection Support' },
      { id: '10', label: 'Causality Calculator' },
      { id: '11', label: 'Safety Chatbot' },
    ],
  },
];

export const getModule = (id) => MODULES.find(m => m.id === id) || null;
