// Top-bar modules and each module's sidebar. Feature labels are the existing step names in each page.
export const MODULES = [
  {
    id: 'design',
    tab: 'DESIGN',
    title: 'Design',
    subtitle: 'Protocol & Study Design',
    features: [
      { id: 'extract', label: 'Protocol Review' },
      { id: 'summary', label: 'Protocol Synopsis' },
      { id: 'eligibility', label: 'Eligibility Criteria Review' },
      { id: 'gaps', label: 'Protocol Gap Assessment' },
      { id: 'feasibility', label: 'Study Feasibility Review' },
      { id: 'recommendations', label: 'Study Design Optimization' },
      { id: 'chat', label: 'Ask AI' },
    ],
  },
  {
    id: 'find',
    tab: 'FIND',
    title: 'Find',
    subtitle: 'Trial Search',
    features: [
      { id: 'results', label: 'Search Results' },
      { id: 'metadata', label: 'Metadata' },
      { id: 'summary', label: 'Summary' },
      { id: 'similar', label: 'Similar Trials' },
      { id: 'comparison', label: 'Comparison' },
      { id: 'recruiting', label: 'Recruiting' },
      { id: 'gaps', label: 'Gaps' },
      { id: 'topics', label: 'Topics' },
      { id: 'dissertation', label: 'Dissertation' },
      { id: 'chat', label: 'Ask AI' },
    ],
  },
  {
    id: 'manage',
    tab: 'MANAGE',
    title: 'Manage',
    subtitle: 'Data Management',
    features: [
      { id: 'crf_review', label: 'CRF Review' },
      { id: 'edit_checks', label: 'Edit Checks' },
      { id: 'query_wording', label: 'Query Wording' },
      { id: 'cleaning_checklist', label: 'Cleaning Checklist' },
      { id: 'medical_coding', label: 'Coding Review' },
      { id: 'dataset_review', label: 'Dataset Review' },
      { id: 'review_summary', label: 'Review Summary' },
    ],
  },
  {
    id: 'analyze',
    tab: 'ANALYSE',
    title: 'Analyse',
    subtitle: 'Biostatistics',
    features: [
      { id: 'study_review', label: 'Study Analysis Review' },
      { id: 'endpoint_summary', label: 'Endpoint Summary' },
      { id: 'sap_outline', label: 'SAP Outline Structure' },
      { id: 'tlf_shells', label: 'TLF Shell Draft Package' },
      { id: 'dataset_checklist', label: 'Dataset Review Checklist' },
      { id: 'descriptive_stats', label: 'Descriptive Statistics' },
      { id: 'clinical_interpretation', label: 'Clinical Interpretation' },
      { id: 'csr_results', label: 'CSR Results Draft' },
      { id: 'chat', label: 'Biostatistician Chat' },
    ],
  },
  {
    id: 'safety',
    tab: 'SAFETY',
    title: 'Safety',
    subtitle: 'Pharmacovigilance',
    features: [
      { id: '1', label: 'Safety Case Review' },
      { id: '2', label: 'SAE Narrative Draft' },
      { id: '3', label: 'Safety Case Summary' },
      { id: '4', label: 'Seriousness & Causality' },
      { id: '5', label: 'MedDRA Coding Support' },
      { id: '6', label: 'Aggregate Safety Summary' },
      { id: '7', label: 'Safety Trend Analysis' },
      { id: '8', label: 'Medical Review Note' },
      { id: '9', label: 'Signal Detection Support' },
      { id: '10', label: 'Causality Calculator' },
      { id: '11', label: 'Safety Chatbot' },
    ],
  },
];

export const getModule = (id) => MODULES.find(m => m.id === id) || null;
